typing: Number function arguments
Number arguments starting at 1 when typing a function application. This
gives context to the user and allows adressing the invidual arguments in
future hint messages.

The previous error message now looks like this:

    File "./test.ml", line 3, characters 23-26:
    3 |   let _ = Hashtbl.find "a" tbl in
                               ^^^
    Error: This constant has type string but an expression was expected of type
             ('a, 'b) Hashtbl.t
           because it is the argument 1 in a function application of type
             ('a, 'b) Hashtbl.t -> 'a -> 'b