WIP: Show full function type when argument couldn't type
This generates error messages like this:

    File "./test.ml", line 3, characters 23-26:
    3 |   let _ = Hashtbl.find "a" tbl in
                               ^^^
    Error: This constant has type string but an expression was expected of type
             ('a, 'b) Hashtbl.t
           because it is in a function application of type
             ('a, 'b) Hashtbl.t -> 'a -> 'b