Print the location and name of the function being applied
This is possibly too much.

    File "./test.ml", line 7, characters 23-26:
    7 |   let _ = Hashtbl.find "a" tbl in
                               ^^^
    Error: This constant has type string but an expression was expected of type
             ('a, 'b) Hashtbl.t
           because it is the argument 1 of the application of
           the function Hashtbl.find.
    File "./test.ml", line 7, characters 10-22:
    7 |   let _ = Hashtbl.find "a" tbl in
                  ^^^^^^^^^^^^
      The function Hashtbl.find, which has type ('a, 'b) Hashtbl.t -> 'a -> 'b.